### ISSUE TITLE
ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by luozhy88** [ikmb/TOFU-MAaPO#14]
This software is very easy to use, but please help me if I encounter some problems now.
  ImportError: cannot import name dataclass_transform
![image](https://github.com/ikmb/TOFU-MAaPO/assets/94740863/bf498eff-fb02-4168-8a66-8ede0251fa5a)
![image](https://github.com/ikmb/TOFU-MAaPO/assets/94740863/e5d8cef6-21a8-492f-b425-24a8e5101f68)
![image](https://github.com/ikmb/TOFU-MAaPO/assets/94740863/ebbcc7fd-766e-4ed0-b9f4-d87157a59fdf)

**Comment by eikematthias** [comment]
Hi, thanks for the issue! Could you provide me with your custom profile (conf/custom.config)? It seems like a dependency is missing in the GTDBTK process, but I cannot reproduce the error with the standard profile as the used container contains all needed dependencies.

**Comment by luozhy88** [comment]
https://github.com/luozhy88/TOFU-MAaPO/blob/main/TOFU-MAaPO-1.40/custom.config

**Comment by eikematthias** [comment]
Two things you can try out: Change line [198](https://github.com/luozhy88/TOFU-MAaPO/blob/c4b081f5f73895189f415090e7e3681c83996cdb/TOFU-MAaPO-1.40/custom.config#L198) to `container = "docker://quay.io/biocontainers/gtdbtk:2.3.2--pyhdfd78af_0"` as this version of GTDB-Tk should fix some dependency problems with pydantic.
or if that does not work, update the GTDB Data to the release 207: https://data.gtdb.ecogenomic.org/releases/release207/207.0/auxillary_files/gtdbtk_r207_v2_data.tar.gz

**Comment by luozhy88** [comment]
I tried two methods, but I still got the same error.
<img width="1398" alt="image" src="https://github.com/ikmb/TOFU-MAaPO/assets/94740863/16515193-dd48-4869-b95b-2637d2440ed1">

**Comment by eikematthias** [comment]
Do you have some local installations of pydantic or gtdbtk that might interfere with the singularity-versions?

**Comment by luozhy88** [comment]
sorry,I don't  know how to install some local installations of pydantic or gtdbtk for singularity img

**Comment by luozhy88** [comment]
Can you solve this bug?
